import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SocialButton from '@/components/SocialButton'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //2.1 Hook area


  //2.2 Function defination area
  const handleSocialLogin = (user) => {
    console.log(user);
  };

  const handleSocialLoginFailure = (err) => {
    console.error(err);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <SocialButton
              provider="google"
              appId="623936552479-5cple32e29sv781c8oaivq2f5efi5t0f.apps.googleusercontent.com"
              onLoginSuccess={handleSocialLogin}
              onLoginFailure={handleSocialLoginFailure}
            >
              Login with Google
            </SocialButton>
        </div>
      </main>
    </>
  )
}
